adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(),
         name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(),
         name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(),
         name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create,
         name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products,
         name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update,
         name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete,
         name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

myShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('orderapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

orderapp/urls.py
from django.urls import path
import orderapp.views as orderapp

app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderList.as_view(), name='order_list'),
    path('forming/complete/<int:pk>/', orderapp.order_forming_complete, name='order_forming_complete'),
    path('create/', orderapp.OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', orderapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', orderapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', orderapp.OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price', orderapp.get_product_price),
]

myShop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def index(request):
    # basket = []
    # if request.user.is_authenticated:
    # basket = Basket.objects.filter (user = request.user)
    # basket = get_basket(user = request.user)
    title = 'myShop'
    # products = Product.objects.all()[:4]
    # 8 запросов за 4мс
    products = Product.objects.filter(is_active=True, category__is_active=True).\
                                        select_related('category')[:4]
    # 4 запроса за 1мс!!!
    links_menu = ['домой', 'продукты', 'контакты', ]
    context_page = {
        'title': title,
        'links_menu': links_menu,
        'products': products,
        # 'basket': basket,
    }
    return render(request, 'myShop/index.html', context=context_page)


def contacts(request):
    # basket = []
    # if request.user.is_authenticated:
    #     basket = Basket.objects.filter (user = request.user)
    # basket = get_basket (user = request.user)
    title = 'контакты'
    links_menu = ['домой', 'продукты', 'контакты', ]
    context_page = {
        'title': title,
        'links_menu': links_menu,
        # 'basket': basket,
    }
    return render(request, 'myShop/contacts.html', context=context_page)

myShop/templates/myShop/includes/main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}" class="{% if request.resolver_match.url_name == link.href %}
active
{% endif %}">{{ links_menu.0 }}</a></li>
    <li><a href="{% url 'products:index' %}" class="{% if request.resolver_match.url_name == link.href %}
active
{% endif %}">{{ links_menu.1 }}</a></li>
    <li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.url_name == link.href %}
active
{% endif %}">{{ links_menu.2 }}</a></li>
    <li>
        {% if user.is_authenticated %}
            <div class="dropdown">
                <a class="btn dropdown-toggle" style="display: inline" role="button" id="dropdownMenuLink"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    {% if user.is_superuser %}
                        <li class="dropdown-item">
                            <a href="{% url 'admin_staff:users' %}">
                                Админка
                            </a>
                        </li>
                    {% endif %}
                    <li class="dropdown-item">
                        <a href="{% url 'auth:edit' %}">
                            Профиль
                        </a>
                    </li>
                    <li class="dropdown-item">
                        <a href="{% url 'orderapp:order_list' %}">
                            Заказы</a>
                    </li>
                    <li class="dropdown-item">
                        <a href="{% url 'auth:logout' %}">выйти</a>
                    </li>
                </ul>
            </div>
        {% else %}
            <li>
                <a href="{% url 'auth:login' %}">войти</a>
            </li>
        {% endif %}
</ul>
<a href="#" class="search"></a>
{% if user.is_authenticated %}
    <a href="{% url 'basket:index' %}" class="basket">
                <span>
                <br>
                    {% if basket %}
                        {{ basket.0.total_cost|floatformat:0 }} руб.
                        ({{ basket.0.total_quantity }} шт.)
                    {% endif %}
                </span>
    </a>
{% endif %}