basketapp/urls.py
from django.urls import path

# from .views import products

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='index'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

# urlpatterns = [
#     path('', products, name='index'),
#     path('category/<int:pk>/', products, name='category'),
# ]

mainapp/urls.py
from django.urls import path

from .views import products, product_detail
from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    # path('category/<int:pk>/page/<int:page>/', products, name='page'), # to cached
    path('category/<int:pk>/page/<int:page>/', cache_page(3600)(products), name='page'),
    path('product_detail/<int:pk>/', product_detail, name='product_detail'),
]

myShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('orderapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(db_index=True,default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория продукта',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        verbose_name='изображение',
        upload_to='products_images',
        blank=True, )
    short_desc = models.CharField(
        verbose_name='короткое описание',
        max_length=60,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='стоимость продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    is_active = models.BooleanField(db_index=True,default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'
# Create your models here.

mainapp/views.py
import random

from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.shortcuts import render, get_object_or_404

from mainapp.models import Product, ProductCategory

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache # если не хотим кэшировать какую то функцию


def get_links_menu():
    """
    функция для кэша по memocached
    """
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    """
    функция для кэша по memocached
    """
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        _category_cached = cache.get(key)
        if _category_cached is None:
            _category_cached = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, _category_cached)
        return _category_cached
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    """
    функция для кэша по memocached
    """
    if settings.LOW_CACHE:
        key = 'products'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True)
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True)


def get_product(pk):
    """
    функция для кэша по memocached
    """
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        _product = cache.get(key)
        if _product is None:
            _product = get_object_or_404(Product, pk=pk)
            cache.set(key, _product)
        return _product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orderd_by_price():
    """
    функция для кэша по memocached
    """
    if settings.LOW_CACHE:
        key = 'products_orderd_by_price'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orderd_by_price(pk):
    """
    функция для кэша по memocached
    """
    if settings.LOW_CACHE:
        key = f'products_in_category_orderd_by_price_{pk}'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True)\
                .order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True)\
                .order_by('price')


def get_hot_product():
    # products = Product.objects.all() кэшируем
    products = get_products()
    return random.sample(list(products), 1)[0]



def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products

@cache_page(3600)
def products(request, pk=None, page=1):
    title = 'каталог'
    links_menu = ['домой', 'продукты', 'контакты', ]
    # cat_products = ProductCategory.objects.all() # to cached
    cat_products = get_links_menu()
    # basket = get_basket(user = request.user)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    # products = Product.objects.all().order_by('price') # to cached
    products = get_products_orderd_by_price()
    # basket = []
    # if request.user.is_authenticated:
    #     basket = Basket.objects.filter (user = request.user)
    #     [
    # {'href': 'products_all', 'name': 'все'},
    # {'href': 'products_home', 'name': 'дом'},
    # {'href': 'products_office', 'name': 'офис'},
    # {'href': 'products_modern', 'name': 'модерн'},
    # {'href': 'products_classic', 'name': 'классика'},
    # ]
    # product = Product.objects.get(id=pk)
    if pk is not None:
        if pk == 0:
            # products = Product.objects.all().order_by('price') # to cached
            products = get_products_orderd_by_price()
            category = {
                'pk': 0,
                'name': 'все'}
        else:
            # category = get_object_or_404(ProductCategory, pk=pk) # to cached
            category = get_category(pk)
            # products = Product.objects.filter(category__pk=pk).order_by('price') # to cached
            products = get_products_in_category_orderd_by_price(pk)

        paginator = Paginator(products, 1)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context_page = {
            'title': title,
            'links_menu': links_menu,
            'cat_products': cat_products,
            'category': category,
            'products': products_paginator,
            'hot_product': hot_product,
            # 'basket': basket,
            'same_products': same_products,
        }
        return render(request, 'mainapp/products.html', context=context_page)

    # products = Product.objects.all()

    context_page = {
        'title': title,
        'links_menu': links_menu,
        'cat_products': cat_products,
        'hot_product': hot_product,
        'products': products,
        'same_products': same_products,
        # 'basket': basket,
    }
    return render(request, 'mainapp/products.html', context=context_page)


def product_detail(request, pk):
    title = 'Выбранный продукт'
    links_menu = ['домой', 'продукты', 'контакты', ]
    # cat_products = ProductCategory.objects.all() # to cached
    cat_products = get_links_menu()
    # basket = get_basket (user = request.user)
    # product = get_object_or_404(Product, pk=pk) # to cached
    product = get_product(pk)
    context_page = {
        'title': title,
        'links_menu': links_menu,
        'cat_products': cat_products,
        'product': product,
        # 'basket': basket,
    }
    return render(request, 'mainapp/product_detail.html', context=context_page)

# вспомогательная, для ловли и вывода в консоль
def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


# данный сигнал позволяет отслеживать is_active и в админке django-ской
@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True) #product_set это выборка с дочерних элементов, как например select_related
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)
# Create your views here.

mainapp/templates/mainapp/product_detail.html
{% extends 'myShop/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block inn %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'myShop/includes/main_menu.html' %}
            {#        <a href="#" class="basket"></a>#}
        </div>
    </div>

    <div class="details">
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <a href="{% url 'basket:add' pk=product.pk %}">
                        {#                <img src="{% static '/mainapp/img/slider1.jpg' %}">#}
                        <img src="/media/{{ product.image }}">
                    </a>
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="" class="slider-control-min">
                            <div class="text">1</div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="" class="slider-control-min">
                            <div class="text">2</div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="" class="slider-control-min">
                            <div class="text">3</div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <h3 class="red">горячее предложение {% now "d.m.Y" %}</h3>
                <p class="price">{{ product.price }}<span>руб</span></p>
                <a href="{% url 'basket:add' pk=product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ product.short_desc }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'myShop/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block inn %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'myShop/includes/main_menu.html' %}
            {#        <a href="#" class="basket"></a>#}
        </div>
    </div>

    <div class="details">
        <div class="links clearfix">
            <ul class="links-menu">

                <!--            <li><a href="#" class="active">все</a></li>-->
                <!--            <li><a href="#">дом</a></li>-->
                <!--            <li><a href="#">офис</a></li>-->
                <!--            <li><a href="#">модерн</a></li>-->
                <!--            <li><a href="#">классика</a></li>-->
                <li><a href="{% url 'products:category' 0 %}"
                       class="{% if request.resolver_match.kwargs.pk == 0 %} active
            {% endif %} ">
                    все
                </a>
                </li>
                {% for cat_product in cat_products %}
                    <li>
                        <a href="{% url 'products:category' cat_product.pk %}"
                           class="{% if request.resolver_match.kwargs.pk|add:'0' == cat_product.pk %} active
                                        {% endif %}">
                            {{ cat_product.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <a href="{% url 'mainapp:product_detail' pk=hot_product.pk %}">
                        {#                <img src="{% static '/mainapp/img/slider1.jpg' %}">#}
                        <img src="/media/{{ hot_product.image }}">
                    </a>
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="{% url 'mainapp:product_detail' pk=hot_product.pk %}">
                            <img src="/media/{{ hot_product.image }}" alt="" class="slider-control-min">
                            <div class="text">1</div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'mainapp:product_detail' pk=hot_product.pk %}">
                            <img src="/media/{{ hot_product.image }}" alt="" class="slider-control-min">
                            <div class="text">2</div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'mainapp:product_detail' pk=hot_product.pk %}">
                            <img src="/media/{{ hot_product.image }}" alt="" class="slider-control-min">
                            <div class="text">3</div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение {% now "d.m.Y" %}</h3>
                <p class="price">{{ hot_product.price }}<span>руб</span></p>
                <a href="{% url 'basket:add' pk=hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.short_desc }}</p>
                </div>
            </div>
        </div>

        <div class="products_list">
            <div class="title clearfix">
                {% if category %}
                    <h2>
                        Категория: "{{ category.name|title }}"
                    </h2>
                {% endif %}
            </div>
            <br>
            {#        <div class="category-products clearfix">#}
            <div class="related-products clearfix">

                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                            <
                        </a>
                    {% endif %}
                    <span class="current">
                                    страница {{ products.number }} из
                                    {{ products.paginator.num_pages }}
                                </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">
                            >
                        </a>
                    {% endif %}
                </div>

                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'mainapp:product_detail' pk=product.pk %}">
                            <img src="/media/{{ product.image }}" alt="product">
                            <div class="text">
                                <img src="{% static 'myShop/img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'mainapp:product_detail' pk=product.pk %}"><img src="/media/{{ product.image }}"
                                                                                        alt="">
                            <div class="text">
                                <img src="{% static 'mainapp/img/icon-hover.png' %}" alt="img">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}


            </div>
        </div>
    </div>
{% endblock %}